<?php return array (
  'username' => '200668889',
  'password' => '92snof',
  'admintel' => '13917313860',
  'fastadmin' => '0',
  'fastadmincontent' => '尊敬管理员,业主{mobile}在网站发布了快捷招标！',
  'tendersadmin' => '0',
  'tendersadmincontent' => '尊敬管理员,业主{name}手机{mobile}在网站发布了招标！',
  'tuanadmin' => '0',
  'tuanadmincontent' => '尊敬管理员,业主{name}联系方式{tel}在报名了{title}团购活动！',
  'fast' => '0',
  'fastcontent' => '尊敬{site_name}会员,感谢您在{site_name}发布快捷招标,稍后{site_name}客服会电话与您联系！【{site_name}】',
  'tenders' => '0',
  'tenderscontent' => '尊敬{name}您好,感谢您在{site_name}发布招标,稍后客服会和您确认需求,将会推荐3家优秀企业为您免费量房、免费设计！【{site_name}】',
  'bid' => '0',
  'bidcontent' => '尊敬{name}您好！{company}参加了您的招标项目！请快回到{site_name}进行查看！',
  'choose' => '0',
  'choosecontent' => '尊敬的VIP公司！业主{name}手机{mobile}在招标的时候选择了你们！请速联系业主！【{site_name}】',
  'designer' => '0',
  'designercontent' => '尊敬的{designer}设计师！业主{name}手机{tel}想请您帮助他们进行设计！请速联系业主！【{site_name}】',
  'liangf' => '0',
  'liangfcontent' => '尊敬的{company}！业主{name}手机{tel}想请你们免费帮助他们量房！【{site_name}】',
  'site' => '0',
  'sitecontent' => '尊敬的{company}！业主{name}手机{phone}想参观你们的工地！【{site_name}】',
);?>